transaction.isolation.level = SERIALIZABLE
server.socket.timeout = 30000
java.util.logging.ConsoleHandler.level = FINEST
logging.level.diesel=ALL
diesel.SelectQueryParser.level = FINEST
diesel.QueryParser.level=ALL
diesel.ConditionParser.level = FINEST
max.inmemory.rows = 10000
max.hash.table.size.mb = 512
